# Generated by Django 3.1.7 on 2021-03-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Select a state', 'select a state'), ('Maharashtra', 'Maharashtra'), ('Delhi', 'Delhi'), ('Karnataka', 'Karnataka'), ('Bihar', 'Bihar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Delhi', 'Delhi'), ('Gujarat', 'Gujarat'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Rajasthan', 'Rajasthan'), ('Madhya Pradesh', 'Madhya Pradesh'), ('West Bengal', 'West Bengal'), ('Haryana', 'Haryana'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Telangana', 'Telangana'), ('Odisha', 'Odisha'), ('Assam', 'Assam'), ('Punjab', 'Punjab'), ('Kerala', 'Kerala'), ('Uttarakhand', 'Uttarakhand'), ('Jharkhand', 'Jharkhand')], default='India', max_length=100)),
            ],
        ),
    ]
